// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FM14KyErqWKxVuvgXs7IC2i4-yQBxhY',
    appId: '1:308270973256:web:25153ed4b2e981a9e8b37d',
    messagingSenderId: '308270973256',
    projectId: 'hospitalx-ec8b0',
    authDomain: 'hospitalx-ec8b0.firebaseapp.com',
    storageBucket: 'hospitalx-ec8b0.appspot.com',
    measurementId: 'G-QL6BL7NRJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSVLXqIeMQgwuTYXjZe0yNGBJWu59IC50',
    appId: '1:308270973256:android:87bddb8d5cc9a754e8b37d',
    messagingSenderId: '308270973256',
    projectId: 'hospitalx-ec8b0',
    storageBucket: 'hospitalx-ec8b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdgqzCyS_ds27K9DQottK5px_c5bo2tOE',
    appId: '1:308270973256:ios:e075e2fa8ce76a78e8b37d',
    messagingSenderId: '308270973256',
    projectId: 'hospitalx-ec8b0',
    storageBucket: 'hospitalx-ec8b0.appspot.com',
    iosBundleId: 'dev.geekathon.hospitalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdgqzCyS_ds27K9DQottK5px_c5bo2tOE',
    appId: '1:308270973256:ios:fe7ee1e9bf286bb7e8b37d',
    messagingSenderId: '308270973256',
    projectId: 'hospitalx-ec8b0',
    storageBucket: 'hospitalx-ec8b0.appspot.com',
    iosBundleId: 'dev.geekathon.hospitalx.RunnerTests',
  );
}
